server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        prefer-agent-address: true
        service-name: ${spring.application.name}
    gateway:
#      一般不设置default filter
#      default-filters:
#        - AddResponseHeader=X-Response-Default-Red, Default-Blue
#        - PrefixPath=/httpbin
      routes:
        - id: pay_getById                 # 路由ID, 要求唯一
          uri: lb://cloud-payment-service # 匹配后提供服务的地址
          #          uri: http://localhost:8001 # 匹配后提供服务的地址
          predicates:
            - Path=/pay/gateway/get/**    # 断言, 路径匹配后进行路由
#            - After=2024-04-10T13:14:23.509356900+08:00[Asia/Shanghai]
#            - Before=2024-04-10T13:22:23.509356900+08:00[Asia/Shanghai]
#            - Between=2024-04-10T13:14:23.509356900+08:00[Asia/Shanghai], 2024-04-10T13:23:23.509356900+08:00[Asia/Shanghai]
#            - Cookie=username,hao
#            - Header=X-Request-Id, \d+
#            - Host=**.haoren.com,**.hren.com
#            - Query=username, \d+
#            - RemoteAddr=192.168.3.7/24
#            - Method=GET,POST
#            - MyPredicate=gold
#            - name: MyPredicate
#              args:
#               userType: gold

        - id: pay_getInfo
          uri: lb://cloud-payment-service # 匹配后提供服务的地址
          #          uri: http://localhost:8001 # 匹配后提供服务的地址
          predicates:
            - Path=/pay/gateway/getInfo/**

        - id: pay_getFilter
          uri: lb://cloud-payment-service # 匹配后提供服务的地址
          predicates:
            - Path=/pay/gateway/filter/**
#            - Path=/gateway/filter/**
#            - Path=/XYZ/haoren/{segment}
          filters:
#            - RedirectTo=302, https://www.baidu.com
#            - PrefixPath=/pay
#            - SetPath=/pay/gateway/{segment}
#            - AddRequestHeader=X-Request-hao,Hao
#            - RemoveRequestHeader=sec-fetch-site
#            - SetRequestHeader=sec-fetch-mode,Blue
#            - AddRequestParameter=customerId, 200
#            - RemoveRequestParameter=customerName
#            - AddResponseHeader=test, hao
#            - RemoveResponseHeader=Content-Type
#            - SetResponseHeader=Date,2099-01-01
            - MyFilter=haoren
          #          - CustomSingle=wong
          #  - RedirectTo=302, https://baidu.com
          #  - SetPath=/pay/gateway/{segment}
          #  - PrefixPath=/pay
