server:
  port: 83
spring:
  application:
    name: nacos-order-consume
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos地址

service-url:
  nacos-user-service: http://nacos-pay-provider

feign:
  sentinel:
    enabled: true